### ISSUE TITLE
Choose testing framework

### ISSUE THREAD

**Issue by svenvanhal** [svenvanhal/key2time#19]
Which (unit) test framework to choose? Have to meet with Key2Soft about their current solution.

Also, check which mocking library is the most feature complete for C#.

**Comment by karimosman** [comment]
https://en.wikipedia.org/wiki/Visual_Studio_Unit_Testing_Framework

**Comment by svenvanhal** [comment]
MSTest: old but stable

NUnit: faster, more readable and with more features. Has VS2017 integration.

xUnit: Little bit difficult / opinionated with Facts and Theories instead of regular tests.

Consensus on the internet: pick whichever you like best. Let's go with NUnit.

**Comment by karimosman** [comment]
We will use NUnit, lekker sven

**Comment by svenvanhal** [comment]
Also, MSTest does not work with Travis-CI.
